/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darke.tpfinalagenda.ui.ventanas;



import com.darke.tpfinalagenda.logicaNegocio.controladores.AgendaControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.AnfitrionControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.LocacionControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.PersonaControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.TipoEventoControlador;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Agenda;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Anfitrion;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Locacion;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Persona;
import com.darke.tpfinalagenda.logicaNegocio.objetos.TipoEvento;
import com.darke.tpfinalagenda.ui.grillas.GrillaAbmAgendas;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Darkeruz
 */
public class AbmAgendas extends javax.swing.JInternalFrame {
    AnfitrionControlador anfitrionControlador = new AnfitrionControlador();
    AgendaControlador agendaControlador = new AgendaControlador();
    LocacionControlador locacionControlador = new LocacionControlador();
    PersonaControlador personaControlador = new PersonaControlador();
    TipoEventoControlador tipoEventoControlador = new TipoEventoControlador();
    Agenda agenda = new Agenda();
    
    int contador = 0;

    /**
     * Creates new form PreAbmPersona
     */
    public AbmAgendas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agendaControlador1 = new com.darke.tpfinalagenda.logicaNegocio.controladores.AgendaControlador();
        anfitrionControlador1 = new com.darke.tpfinalagenda.logicaNegocio.controladores.AnfitrionControlador();
        locacionControlador1 = new com.darke.tpfinalagenda.logicaNegocio.controladores.LocacionControlador();
        personaControlador1 = new com.darke.tpfinalagenda.logicaNegocio.controladores.PersonaControlador();
        tipoEventoControlador1 = new com.darke.tpfinalagenda.logicaNegocio.controladores.TipoEventoControlador();
        agenda1 = new com.darke.tpfinalagenda.logicaNegocio.objetos.Agenda();
        anfitrion1 = new com.darke.tpfinalagenda.logicaNegocio.objetos.Anfitrion();
        locacion1 = new com.darke.tpfinalagenda.logicaNegocio.objetos.Locacion();
        persona1 = new com.darke.tpfinalagenda.logicaNegocio.objetos.Persona();
        tipoEvento1 = new com.darke.tpfinalagenda.logicaNegocio.objetos.TipoEvento();
        grillaAbmAgendas1 = new com.darke.tpfinalagenda.ui.grillas.GrillaAbmAgendas();
        jPanel1 = new javax.swing.JPanel();
        jbModificar = new javax.swing.JButton();
        jbVer = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableListadoAgendas = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbVer.setText("Ver");
        jbVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVer)
                    .addComponent(jbCerrar)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addContainerGap())
        );

        jtableListadoAgendas.setModel(grillaAbmAgendas1);
        jtableListadoAgendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableListadoAgendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableListadoAgendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerActionPerformed
        // TODO add your handling code here:
        ArrayList<Agenda> agendas = new ArrayList<>();
        try {
            agendas = agendaControlador.extraerTodos();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        GrillaAbmAgendas grillaAbmAgendas = new GrillaAbmAgendas(agendas);
        jtableListadoAgendas.setModel(grillaAbmAgendas);
    }//GEN-LAST:event_jbVerActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        try {
            ModificarDatosDB modificarDatosDB = new ModificarDatosDB((int)jtableListadoAgendas.getValueAt(jtableListadoAgendas.getSelectedRow(), 0));
            modificarDatosDB.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Primero debe presionar en 'Ver' y luego elegir una fila de la tabla!");
        }
        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jtableListadoAgendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableListadoAgendasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableListadoAgendasMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        try {
            EliminarDatosDB eliminarDatosDB = new EliminarDatosDB((int) jtableListadoAgendas.getValueAt(jtableListadoAgendas.getSelectedRow(),0));
            eliminarDatosDB.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Primero debe presionar en 'Ver' y luego elegir una fila de la tabla!");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.darke.tpfinalagenda.logicaNegocio.objetos.Agenda agenda1;
    private com.darke.tpfinalagenda.logicaNegocio.controladores.AgendaControlador agendaControlador1;
    private com.darke.tpfinalagenda.logicaNegocio.objetos.Anfitrion anfitrion1;
    private com.darke.tpfinalagenda.logicaNegocio.controladores.AnfitrionControlador anfitrionControlador1;
    private com.darke.tpfinalagenda.ui.grillas.GrillaAbmAgendas grillaAbmAgendas1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbVer;
    private javax.swing.JTable jtableListadoAgendas;
    private com.darke.tpfinalagenda.logicaNegocio.objetos.Locacion locacion1;
    private com.darke.tpfinalagenda.logicaNegocio.controladores.LocacionControlador locacionControlador1;
    private com.darke.tpfinalagenda.logicaNegocio.objetos.Persona persona1;
    private com.darke.tpfinalagenda.logicaNegocio.controladores.PersonaControlador personaControlador1;
    private com.darke.tpfinalagenda.logicaNegocio.objetos.TipoEvento tipoEvento1;
    private com.darke.tpfinalagenda.logicaNegocio.controladores.TipoEventoControlador tipoEventoControlador1;
    // End of variables declaration//GEN-END:variables
}
