/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darke.tpfinalagenda.ui.ventanas;

import com.darke.tpfinalagenda.logicaNegocio.controladores.LocacionControlador;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Locacion;

/**
 *
 * @author Darkeruz
 */
public class DatosLocacionFormulario extends javax.swing.JFrame {
    int id_agenda;

    /**
     * Creates new form DatosLocacionFormulario
     */
    public DatosLocacionFormulario() {
        initComponents();
    }
    
    public DatosLocacionFormulario(int id_agenda){
        this.id_agenda = id_agenda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlNombreLocacion = new javax.swing.JLabel();
        jlDomicilioLocacion = new javax.swing.JLabel();
        jlEstadoLocacion = new javax.swing.JLabel();
        jtNombreLocacion = new javax.swing.JTextField();
        jtDomicilioLocacion = new javax.swing.JTextField();
        jcbLocacion = new javax.swing.JComboBox<>();
        jbModificarLocacion = new javax.swing.JButton();
        jlLocacionAgregado = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Locación"));

        jlNombreLocacion.setText("Nombre:");

        jlDomicilioLocacion.setText("Domicilio:");

        jlEstadoLocacion.setText("Estado:");

        jcbLocacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));
        jcbLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLocacionActionPerformed(evt);
            }
        });

        jbModificarLocacion.setText("Modificar");
        jbModificarLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarLocacionActionPerformed(evt);
            }
        });

        jlLocacionAgregado.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlDomicilioLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDomicilioLocacion)
                .addGap(6, 6, 6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlNombreLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtNombreLocacion)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlEstadoLocacion)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jbModificarLocacion)
                        .addGap(18, 18, 18)
                        .addComponent(jlLocacionAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcbLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreLocacion)
                    .addComponent(jtNombreLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDomicilioLocacion)
                    .addComponent(jtDomicilioLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoLocacion)
                    .addComponent(jcbLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificarLocacion)
                    .addComponent(jlLocacionAgregado))
                .addContainerGap())
        );

        jlTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlTitulo.setText("Modifique nombre, domicilio y estado.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLocacionActionPerformed

    private void jbModificarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarLocacionActionPerformed
        // TODO add your handling code here:
        String nombreLocacion, domicilioLocacion;
        boolean estadoLocacion;
        nombreLocacion = jtNombreLocacion.getText();
        domicilioLocacion = jtDomicilioLocacion.getText();
        estadoLocacion = "Disponible".equals(jcbLocacion.getSelectedItem().toString());
        Locacion locacion = new Locacion(nombreLocacion, domicilioLocacion, estadoLocacion);
        locacion.setId(id_agenda);
        
        try {
            LocacionControlador locacionControlador = new LocacionControlador();
            locacionControlador.modificar(locacion);
            javax.swing.JOptionPane.showMessageDialog(this, "Datos modificados correctamente.");
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jbModificarLocacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosLocacionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosLocacionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosLocacionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosLocacionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosLocacionFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbModificarLocacion;
    private javax.swing.JComboBox<String> jcbLocacion;
    private javax.swing.JLabel jlDomicilioLocacion;
    private javax.swing.JLabel jlEstadoLocacion;
    private javax.swing.JLabel jlLocacionAgregado;
    private javax.swing.JLabel jlNombreLocacion;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtDomicilioLocacion;
    private javax.swing.JTextField jtNombreLocacion;
    // End of variables declaration//GEN-END:variables
}
