/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darke.tpfinalagenda.ui.ventanas;

import com.darke.tpfinalagenda.logicaNegocio.controladores.TipoEventoControlador;
import com.darke.tpfinalagenda.logicaNegocio.objetos.TipoEvento;

/**
 *
 * @author Darkeruz
 */
public class DatosEventoFormulario extends javax.swing.JFrame {
    int id_agenda;

    /**
     * Creates new form DatosEventoFormulario
     */
    public DatosEventoFormulario() {
        initComponents();
    }
    
    public DatosEventoFormulario(int id_agenda){
        this.id_agenda = id_agenda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jlNombreTipoEvento = new javax.swing.JLabel();
        jlEstadoTipoEvento = new javax.swing.JLabel();
        jtNombreTipoEvento = new javax.swing.JTextField();
        jcbTipoEvento = new javax.swing.JComboBox<>();
        jbModificarTipoEvento = new javax.swing.JButton();
        jlTipoEventoAgregado = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de evento"));

        jlNombreTipoEvento.setText("Nombre:");

        jlEstadoTipoEvento.setText("Estado:");

        jcbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reunión", "Consulta" }));
        jcbTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoEventoActionPerformed(evt);
            }
        });

        jbModificarTipoEvento.setText("Modificar");
        jbModificarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarTipoEventoActionPerformed(evt);
            }
        });

        jlTipoEventoAgregado.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlNombreTipoEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNombreTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbModificarTipoEvento)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlEstadoTipoEvento)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addComponent(jlTipoEventoAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreTipoEvento)
                    .addComponent(jtNombreTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoTipoEvento)
                    .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificarTipoEvento)
                    .addComponent(jlTipoEventoAgregado))
                .addContainerGap())
        );

        jlTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlTitulo.setText("Modifique nombre y estado.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlTitulo)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarTipoEventoActionPerformed
        // TODO add your handling code here:
        String nombreTipoEvento;
        boolean estadoTipoEvento;
        nombreTipoEvento = jtNombreTipoEvento.getText();
        estadoTipoEvento = "Reunión".equals(jcbTipoEvento.getSelectedItem().toString());
        TipoEvento tipoEvento = new TipoEvento(nombreTipoEvento, estadoTipoEvento);
        tipoEvento.setId(id_agenda);
        
        try {
            TipoEventoControlador tipoEventoControlador = new TipoEventoControlador();
            tipoEventoControlador.modificar(tipoEvento);
            javax.swing.JOptionPane.showMessageDialog(this, "Datos modificados correctamente.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jbModificarTipoEventoActionPerformed

    private void jcbTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEventoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEventoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEventoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEventoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEventoFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbModificarTipoEvento;
    private javax.swing.JComboBox<String> jcbTipoEvento;
    private javax.swing.JLabel jlEstadoTipoEvento;
    private javax.swing.JLabel jlNombreTipoEvento;
    private javax.swing.JLabel jlTipoEventoAgregado;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtNombreTipoEvento;
    // End of variables declaration//GEN-END:variables
}
