/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darke.tpfinalagenda.ui.ventanas;

import com.darke.tpfinalagenda.logicaNegocio.controladores.AnfitrionControlador;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Agenda;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Anfitrion;
import java.util.ArrayList;

/**
 *
 * @author Darkeruz
 */
public class DatosAnfitrionFormulario extends javax.swing.JFrame {
    int id_agenda;
    int contadorAnfitrion=0;
    Agenda agenda = new Agenda();

    /**
     * Creates new form DatosAnfitrionFormulario
     */
    public DatosAnfitrionFormulario() {
        initComponents();
    }
    
    public DatosAnfitrionFormulario(int id_agenda){
        this.id_agenda = id_agenda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jlApellidoAnfitrion = new javax.swing.JLabel();
        jtApellidoAnfitrion = new javax.swing.JTextField();
        jlNombreAnfitrion = new javax.swing.JLabel();
        jtNombreAnfitrion = new javax.swing.JTextField();
        jbAgregarAnfitrion = new javax.swing.JButton();
        jlAnfitrionAgregados = new javax.swing.JLabel();
        jlContadorAnfitrion = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Anfitrion"));

        jlApellidoAnfitrion.setText("Apellido:");

        jlNombreAnfitrion.setText("Nombre:");

        jbAgregarAnfitrion.setText("Agregar");
        jbAgregarAnfitrion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarAnfitrionActionPerformed(evt);
            }
        });

        jlAnfitrionAgregados.setText("Agregados:");

        jlContadorAnfitrion.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlNombreAnfitrion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNombreAnfitrion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jlApellidoAnfitrion)
                        .addGap(18, 18, 18)
                        .addComponent(jtApellidoAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jbAgregarAnfitrion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAnfitrionAgregados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlContadorAnfitrion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellidoAnfitrion)
                    .addComponent(jtApellidoAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreAnfitrion)
                    .addComponent(jtNombreAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarAnfitrion)
                    .addComponent(jlAnfitrionAgregados)
                    .addComponent(jlContadorAnfitrion))
                .addContainerGap())
        );

        jlTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlTitulo.setText("Modifique apellido y nombre");

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbModificar)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlTitulo)
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarAnfitrionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarAnfitrionActionPerformed
        // TODO add your handling code here:
        String apellidoAnfitrion, nombreAnfitrion;
        apellidoAnfitrion = jtApellidoAnfitrion.getText();
        nombreAnfitrion = jtNombreAnfitrion.getText();
        Anfitrion anfitrion = new Anfitrion(apellidoAnfitrion, nombreAnfitrion);
        anfitrion.setId_agenda(id_agenda);
        agenda.addAnfitrion(anfitrion);
        ++contadorAnfitrion;
        String contadorAnfitrionString = String.valueOf(contadorAnfitrion);
        jlContadorAnfitrion.setText(contadorAnfitrionString);
        jtApellidoAnfitrion.setText("");
        jtNombreAnfitrion.setText("");
        
       
    }//GEN-LAST:event_jbAgregarAnfitrionActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        AnfitrionControlador anfitrionControlador = new AnfitrionControlador();
        ArrayList<Anfitrion> listadoAnfitrionNuevos;
        listadoAnfitrionNuevos = agenda.getListaAnfitrion();
        anfitrionControlador.eliminarTodo(id_agenda);
        
        for(Anfitrion anfitriones : listadoAnfitrionNuevos){
            anfitrionControlador.crear(anfitriones);
        }
        
    }//GEN-LAST:event_jbModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosAnfitrionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosAnfitrionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosAnfitrionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosAnfitrionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosAnfitrionFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbAgregarAnfitrion;
    private javax.swing.JButton jbModificar;
    private javax.swing.JLabel jlAnfitrionAgregados;
    private javax.swing.JLabel jlApellidoAnfitrion;
    private javax.swing.JLabel jlContadorAnfitrion;
    private javax.swing.JLabel jlNombreAnfitrion;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtApellidoAnfitrion;
    private javax.swing.JTextField jtNombreAnfitrion;
    // End of variables declaration//GEN-END:variables
}
