/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darke.tpfinalagenda.ui.ventanas;

import com.darke.tpfinalagenda.logicaNegocio.controladores.AgendaControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.AnfitrionControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.LocacionControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.PersonaControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.TipoEventoControlador;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Agenda;
import javax.swing.JOptionPane;
import org.postgresql.util.PSQLException;

/**
 *
 * @author Darkeruz
 */
public class EliminarDatosDB extends javax.swing.JFrame {
    int id_agenda;

    /**
     * Creates new form EliminarDatosDB
     */
    public EliminarDatosDB() {
        initComponents();
    }
    
    public EliminarDatosDB(int id_agenda){
        this.id_agenda = id_agenda;
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbFechaHora = new javax.swing.JButton();
        jbAnfitrion = new javax.swing.JButton();
        jbLocacion = new javax.swing.JButton();
        jbInvitados = new javax.swing.JButton();
        jbEvento = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Elija los datos de la agenda a eliminar");

        jbFechaHora.setText("Agenda");
        jbFechaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechaHoraActionPerformed(evt);
            }
        });

        jbAnfitrion.setText("Datos del Anfitrión");
        jbAnfitrion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnfitrionActionPerformed(evt);
            }
        });

        jbLocacion.setText("Datos de Locación");
        jbLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLocacionActionPerformed(evt);
            }
        });

        jbInvitados.setText("Invitados");
        jbInvitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInvitadosActionPerformed(evt);
            }
        });

        jbEvento.setText("Datos del Evento");
        jbEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEventoActionPerformed(evt);
            }
        });

        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setText("Antes de eliminar la agenda");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setText("elimina los otros campos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jbAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbInvitados, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbInvitados, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(jbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFechaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechaHoraActionPerformed
        // TODO add your handling code here:
        
        AgendaControlador agendaControlador = new AgendaControlador();
        Agenda agenda = new Agenda();
        agenda.setId(id_agenda);
        try {
            agendaControlador.eliminar(agenda);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Antes de liminar la agenda debes eliminar los otros campos.");
        }
        

    }//GEN-LAST:event_jbFechaHoraActionPerformed

    private void jbAnfitrionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnfitrionActionPerformed
        // TODO add your handling code here:
        try {
            AnfitrionControlador anfitrionControlador = new AnfitrionControlador();
            anfitrionControlador.eliminarTodo(id_agenda);
            JOptionPane.showMessageDialog(rootPane, "Datos borrados!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo borrar!");
        }
        
        

    }//GEN-LAST:event_jbAnfitrionActionPerformed

    private void jbLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLocacionActionPerformed
        // TODO add your handling code here:
        try {
            LocacionControlador locacionControlador = new LocacionControlador();
            locacionControlador.eliminarPorId(id_agenda);
            JOptionPane.showMessageDialog(rootPane, "Datos borrados!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo borrar!");
        }
        
        

    }//GEN-LAST:event_jbLocacionActionPerformed

    private void jbInvitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInvitadosActionPerformed
        // TODO add your handling code here:
        try {
            PersonaControlador invitadosControlador = new PersonaControlador();
            invitadosControlador.eliminarTodo(id_agenda);
            JOptionPane.showMessageDialog(rootPane, "Datos borrados!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo borrar!");
        }
        
        
    }//GEN-LAST:event_jbInvitadosActionPerformed

    private void jbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEventoActionPerformed
        // TODO add your handling code here:
        try {
            TipoEventoControlador tipoEventoControlador = new TipoEventoControlador();
            tipoEventoControlador.eliminarPorId(id_agenda);
            JOptionPane.showMessageDialog(rootPane, "Datos borrados!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo borrar!");
        }
        
        
    }//GEN-LAST:event_jbEventoActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarDatosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarDatosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarDatosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarDatosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarDatosDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAnfitrion;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEvento;
    private javax.swing.JButton jbFechaHora;
    private javax.swing.JButton jbInvitados;
    private javax.swing.JButton jbLocacion;
    // End of variables declaration//GEN-END:variables
}
