/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darke.tpfinalagenda.ui.ventanas;

import com.darke.tpfinalagenda.logicaNegocio.controladores.AgendaControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.AnfitrionControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.LocacionControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.PersonaControlador;
import com.darke.tpfinalagenda.logicaNegocio.controladores.TipoEventoControlador;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Agenda;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Anfitrion;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Locacion;
import com.darke.tpfinalagenda.logicaNegocio.objetos.Persona;
import com.darke.tpfinalagenda.logicaNegocio.objetos.TipoEvento;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Darkeruz
 */
public class JifCrearAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifCrearAgenda
     */
    Agenda agenda = new Agenda();
    int contadorAnfitrion = 0, contadorInvitados = 0;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    AgendaControlador agendaControlador = new AgendaControlador();
    LocacionControlador locacionControlador = new LocacionControlador();
    TipoEventoControlador tipoEventoControlador = new TipoEventoControlador();
    AnfitrionControlador anfitrionControlador = new AnfitrionControlador();
    PersonaControlador personaControlador = new PersonaControlador();
    public JifCrearAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlApellidoInvitado = new javax.swing.JLabel();
        jlNombreInvitado = new javax.swing.JLabel();
        jbAgregarInvitado = new javax.swing.JButton();
        jtApellidoInvitado = new javax.swing.JTextField();
        jtNombreInvitado = new javax.swing.JTextField();
        jlInvitadosAgregados = new javax.swing.JLabel();
        jlContadorInvitados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlNombreLocacion = new javax.swing.JLabel();
        jlDomicilioLocacion = new javax.swing.JLabel();
        jlEstadoLocacion = new javax.swing.JLabel();
        jtNombreLocacion = new javax.swing.JTextField();
        jtDomicilioLocacion = new javax.swing.JTextField();
        jcbLocacion = new javax.swing.JComboBox<>();
        jbAgregarLocacion = new javax.swing.JButton();
        jlLocacionAgregado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlNombreTipoEvento = new javax.swing.JLabel();
        jlEstadoTipoEvento = new javax.swing.JLabel();
        jtNombreTipoEvento = new javax.swing.JTextField();
        jcbTipoEvento = new javax.swing.JComboBox<>();
        jbAgregarTipoEvento = new javax.swing.JButton();
        jlTipoEventoAgregado = new javax.swing.JLabel();
        jlFechaAgenda = new javax.swing.JLabel();
        jlHoraAgenda = new javax.swing.JLabel();
        jcbHoraAgenda = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jlApellidoAnfitrion = new javax.swing.JLabel();
        jtApellidoAnfitrion = new javax.swing.JTextField();
        jlNombreAnfitrion = new javax.swing.JLabel();
        jtNombreAnfitrion = new javax.swing.JTextField();
        jbAgregarAnfitrion = new javax.swing.JButton();
        jlAnfitrionAgregado = new javax.swing.JLabel();
        jlContadorAnfitrion = new javax.swing.JLabel();
        jbCrearAgenda = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel1.setText("Crear Agenda");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Invitados"));

        jlApellidoInvitado.setText("Apellido:");

        jlNombreInvitado.setText("Nombre:");

        jbAgregarInvitado.setText("Agregar");
        jbAgregarInvitado.setEnabled(false);
        jbAgregarInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarInvitadoActionPerformed(evt);
            }
        });

        jtApellidoInvitado.setEnabled(false);

        jtNombreInvitado.setEnabled(false);

        jlInvitadosAgregados.setForeground(new java.awt.Color(0, 0, 51));
        jlInvitadosAgregados.setText("Invitados agregados:");

        jlContadorInvitados.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlApellidoInvitado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtApellidoInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlNombreInvitado)
                            .addGap(19, 19, 19)
                            .addComponent(jtNombreInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAgregarInvitado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlInvitadosAgregados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlContadorInvitados, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellidoInvitado)
                    .addComponent(jtApellidoInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreInvitado)
                    .addComponent(jtNombreInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarInvitado)
                    .addComponent(jlInvitadosAgregados)
                    .addComponent(jlContadorInvitados))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Locación"));

        jlNombreLocacion.setText("Nombre:");

        jlDomicilioLocacion.setText("Domicilio:");

        jlEstadoLocacion.setText("Estado:");

        jtNombreLocacion.setEnabled(false);

        jtDomicilioLocacion.setEnabled(false);

        jcbLocacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));
        jcbLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLocacionActionPerformed(evt);
            }
        });

        jbAgregarLocacion.setText("Agregar");
        jbAgregarLocacion.setEnabled(false);
        jbAgregarLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarLocacionActionPerformed(evt);
            }
        });

        jlLocacionAgregado.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlDomicilioLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDomicilioLocacion)
                .addGap(6, 6, 6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlEstadoLocacion)
                .addGap(18, 18, 18)
                .addComponent(jcbLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlNombreLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtNombreLocacion)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAgregarLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLocacionAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreLocacion)
                    .addComponent(jtNombreLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDomicilioLocacion)
                    .addComponent(jtDomicilioLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoLocacion)
                    .addComponent(jcbLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarLocacion)
                    .addComponent(jlLocacionAgregado))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de evento"));

        jlNombreTipoEvento.setText("Nombre:");

        jlEstadoTipoEvento.setText("Estado:");

        jtNombreTipoEvento.setEnabled(false);

        jcbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reunión", "Consulta" }));
        jcbTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoEventoActionPerformed(evt);
            }
        });

        jbAgregarTipoEvento.setText("Agregar");
        jbAgregarTipoEvento.setEnabled(false);
        jbAgregarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarTipoEventoActionPerformed(evt);
            }
        });

        jlTipoEventoAgregado.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlNombreTipoEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNombreTipoEvento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlEstadoTipoEvento)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jbAgregarTipoEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTipoEventoAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreTipoEvento)
                    .addComponent(jtNombreTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoTipoEvento)
                    .addComponent(jcbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarTipoEvento)
                    .addComponent(jlTipoEventoAgregado))
                .addContainerGap())
        );

        jlFechaAgenda.setText("Fecha:");

        jlHoraAgenda.setText("Hora:");

        jcbHoraAgenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Anfitrion"));

        jlApellidoAnfitrion.setText("Apellido:");

        jlNombreAnfitrion.setText("Nombre:");

        jbAgregarAnfitrion.setText("Agregar");
        jbAgregarAnfitrion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarAnfitrionActionPerformed(evt);
            }
        });

        jlAnfitrionAgregado.setForeground(new java.awt.Color(0, 0, 51));
        jlAnfitrionAgregado.setText("Agregados:");

        jlContadorAnfitrion.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlNombreAnfitrion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNombreAnfitrion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jlApellidoAnfitrion)
                        .addGap(18, 18, 18)
                        .addComponent(jtApellidoAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAgregarAnfitrion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAnfitrionAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlContadorAnfitrion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellidoAnfitrion)
                    .addComponent(jtApellidoAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreAnfitrion)
                    .addComponent(jtNombreAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarAnfitrion)
                    .addComponent(jlAnfitrionAgregado)
                    .addComponent(jlContadorAnfitrion))
                .addGap(28, 28, 28))
        );

        jbCrearAgenda.setText("Crear agenda");
        jbCrearAgenda.setEnabled(false);
        jbCrearAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlFechaAgenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlHoraAgenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbHoraAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbCrearAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbHoraAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlHoraAgenda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlFechaAgenda))
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCrearAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLocacionActionPerformed

    private void jbAgregarAnfitrionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarAnfitrionActionPerformed
        // TODO add your handling code here:
        ArrayList<Agenda> agendas = new ArrayList<>();
        agendas = agendaControlador.extraerTodos();
        int indice = agendas.size();
          
        ++contadorAnfitrion;
        String apellidoAnfitrion, nombreAnfitrion;
        int anfitrionIdAgenda;
        apellidoAnfitrion = jtApellidoAnfitrion.getText();
        nombreAnfitrion = jtNombreAnfitrion.getText();
        anfitrionIdAgenda = agendas.get(indice-1).getId(); //obtenemos el ID de la última agenda de la lista de agendas.
        Anfitrion anfitrion = new Anfitrion(anfitrionIdAgenda, apellidoAnfitrion, nombreAnfitrion);
        agenda.addAnfitrion(anfitrion);
        
        
        String contadorAnfitrionString = String.valueOf(contadorAnfitrion);
        jlContadorAnfitrion.setText(contadorAnfitrionString);
        jtApellidoAnfitrion.setText("");
        jtNombreAnfitrion.setText("");
        
        jtNombreLocacion.setEnabled(true);
        jtDomicilioLocacion.setEnabled(true);
        jbAgregarLocacion.setEnabled(true);
        
    }//GEN-LAST:event_jbAgregarAnfitrionActionPerformed

    private void jbAgregarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarLocacionActionPerformed
        // TODO add your handling code here:
        ArrayList<Agenda> agendas = new ArrayList<>();
        agendas = agendaControlador.extraerTodos();
        int indice = agendas.size();
        int locacionIdAgenda;
        String nombreLocacion, domicilioLocacion;
        boolean estadoLocacion;
        nombreLocacion = jtNombreLocacion.getText();
        domicilioLocacion = jtDomicilioLocacion.getText();
        estadoLocacion = "Disponible".equals(jcbLocacion.getSelectedItem().toString());
        locacionIdAgenda = agendas.get(indice-1).getId();
        
        Locacion locacion = new Locacion(locacionIdAgenda, nombreLocacion, domicilioLocacion, estadoLocacion);
        agenda.setLocacion(locacion);
        try {
            locacionControlador.crear(locacion);
            jlLocacionAgregado.setText("Locación agregada.");
        } catch (Exception e) {
            jlLocacionAgregado.setText("No se pudo agregar.");
        }
        jtNombreLocacion.setEnabled(false);
        jtDomicilioLocacion.setEnabled(false);
        jcbLocacion.setEnabled(false);
        jbAgregarLocacion.setEnabled(false);
        jtNombreTipoEvento.setEnabled(true);
        jbAgregarTipoEvento.setEnabled(true);
    }//GEN-LAST:event_jbAgregarLocacionActionPerformed

    private void jbAgregarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarTipoEventoActionPerformed
        // TODO add your handling code here:
        ArrayList<Agenda> agendas = new ArrayList<>();
        agendas = agendaControlador.extraerTodos();
        int indice = agendas.size();
        int tipoEventoIdAgenda;
        
        String nombreTipoEvento;
        boolean estadoTipoEvento;
        nombreTipoEvento = jtNombreTipoEvento.getText();
        estadoTipoEvento = "Reunión".equals(jcbTipoEvento.getSelectedItem().toString());
        tipoEventoIdAgenda = agendas.get(indice-1).getId();
        
        TipoEvento tipoEvento = new TipoEvento(tipoEventoIdAgenda, nombreTipoEvento, estadoTipoEvento);
        agenda.setTipoevento(tipoEvento);
        try {
            tipoEventoControlador.crear(tipoEvento);
            jlTipoEventoAgregado.setText("Evento agregado.");
        } catch (Exception e) {
            jlTipoEventoAgregado.setText("No se pudo agregar");
        }
        
        jtNombreTipoEvento.setEnabled(false);
        jcbTipoEvento.setEnabled(false);
        jbAgregarTipoEvento.setEnabled(false);
        jtApellidoInvitado.setEnabled(true);
        jtNombreInvitado.setEnabled(true);
        jbAgregarInvitado.setEnabled(true);
        
        
    }//GEN-LAST:event_jbAgregarTipoEventoActionPerformed

    private void jcbTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoEventoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoEventoActionPerformed

    private void jbAgregarInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarInvitadoActionPerformed
        // TODO add your handling code here:
        ++contadorInvitados;
        ArrayList<Agenda> agendas = new ArrayList<>();
        agendas = agendaControlador.extraerTodos();
        int indice = agendas.size();
        
        int invitadoIdAgenda;
        String contadorString= String.valueOf(contadorInvitados);
        String apellidoInvitado, nombreInvitado;
        apellidoInvitado = jtApellidoInvitado.getText();
        nombreInvitado = jtNombreInvitado.getText();
        invitadoIdAgenda = agendas.get(indice-1).getId();
        Persona invitado = new Persona(invitadoIdAgenda, apellidoInvitado, nombreInvitado);
        agenda.addInvitado(invitado);
        jlContadorInvitados.setText(contadorString);
        
        jtApellidoInvitado.setText("");
        jtNombreInvitado.setText("");
        
        
        jDateChooser.setEnabled(true);
        jcbHoraAgenda.setEnabled(true);
        jbCrearAgenda.setEnabled(true);
    }//GEN-LAST:event_jbAgregarInvitadoActionPerformed

    private void jbCrearAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearAgendaActionPerformed
        // TODO add your handling code here:
        agenda.setFecha(formato.format(jDateChooser.getDate()));
        agenda.setHora(jcbHoraAgenda.getSelectedItem().toString());
        int indice;
        ArrayList<Agenda> agendas = new ArrayList<>();
        agendas = agendaControlador.extraerTodos();
        indice = agendas.size();
        agenda.setId(agendas.get(indice-1).getId());
        
        try {
            
            agendaControlador.modificar(agenda);
            for(Anfitrion anfitrion : agenda.getListaAnfitrion()){
                anfitrionControlador.crear(anfitrion);
            }
            
            for(Persona invitado : agenda.getListaInvitados()){
                personaControlador.crear(invitado);
            }
            
            JOptionPane.showMessageDialog(this, "Agenda creada correctamente!");
            jbCrearAgenda.setEnabled(false);
            jtApellidoInvitado.setEnabled(false);
            jtNombreInvitado.setEnabled(false);
            jbAgregarInvitado.setEnabled(false);
            MDIPrincipal mdiPrincipal = new MDIPrincipal();
            this.dispose();
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbCrearAgendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbAgregarAnfitrion;
    private javax.swing.JButton jbAgregarInvitado;
    private javax.swing.JButton jbAgregarLocacion;
    private javax.swing.JButton jbAgregarTipoEvento;
    private javax.swing.JButton jbCrearAgenda;
    private javax.swing.JComboBox<String> jcbHoraAgenda;
    private javax.swing.JComboBox<String> jcbLocacion;
    private javax.swing.JComboBox<String> jcbTipoEvento;
    private javax.swing.JLabel jlAnfitrionAgregado;
    private javax.swing.JLabel jlApellidoAnfitrion;
    private javax.swing.JLabel jlApellidoInvitado;
    private javax.swing.JLabel jlContadorAnfitrion;
    private javax.swing.JLabel jlContadorInvitados;
    private javax.swing.JLabel jlDomicilioLocacion;
    private javax.swing.JLabel jlEstadoLocacion;
    private javax.swing.JLabel jlEstadoTipoEvento;
    private javax.swing.JLabel jlFechaAgenda;
    private javax.swing.JLabel jlHoraAgenda;
    private javax.swing.JLabel jlInvitadosAgregados;
    private javax.swing.JLabel jlLocacionAgregado;
    private javax.swing.JLabel jlNombreAnfitrion;
    private javax.swing.JLabel jlNombreInvitado;
    private javax.swing.JLabel jlNombreLocacion;
    private javax.swing.JLabel jlNombreTipoEvento;
    private javax.swing.JLabel jlTipoEventoAgregado;
    private javax.swing.JTextField jtApellidoAnfitrion;
    private javax.swing.JTextField jtApellidoInvitado;
    private javax.swing.JTextField jtDomicilioLocacion;
    private javax.swing.JTextField jtNombreAnfitrion;
    private javax.swing.JTextField jtNombreInvitado;
    private javax.swing.JTextField jtNombreLocacion;
    private javax.swing.JTextField jtNombreTipoEvento;
    // End of variables declaration//GEN-END:variables
}
